package org.lg.model;

import java.util.Date;

public class Record {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.id
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.creatTime
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Date creattime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.recycleTime
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Date recycletime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.useUser
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Integer useuser;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.sendUser
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Integer senduser;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.marks
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String marks;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column record.recyle
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String recyle;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.id
	 * @return  the value of record.id
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.id
	 * @param id  the value for record.id
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.creatTime
	 * @return  the value of record.creatTime
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Date getCreattime() {
		return creattime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.creatTime
	 * @param creattime  the value for record.creatTime
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.recycleTime
	 * @return  the value of record.recycleTime
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Date getRecycletime() {
		return recycletime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.recycleTime
	 * @param recycletime  the value for record.recycleTime
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setRecycletime(Date recycletime) {
		this.recycletime = recycletime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.useUser
	 * @return  the value of record.useUser
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Integer getUseuser() {
		return useuser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.useUser
	 * @param useuser  the value for record.useUser
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setUseuser(Integer useuser) {
		this.useuser = useuser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.sendUser
	 * @return  the value of record.sendUser
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Integer getSenduser() {
		return senduser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.sendUser
	 * @param senduser  the value for record.sendUser
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setSenduser(Integer senduser) {
		this.senduser = senduser;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.marks
	 * @return  the value of record.marks
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getMarks() {
		return marks;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.marks
	 * @param marks  the value for record.marks
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setMarks(String marks) {
		this.marks = marks;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column record.recyle
	 * @return  the value of record.recyle
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getRecyle() {
		return recyle;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column record.recyle
	 * @param recyle  the value for record.recyle
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setRecyle(String recyle) {
		this.recyle = recyle;
	}
}