package org.lg.model;

public class User {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.id
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.userName
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.passWord
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.name
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.credit
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private Integer credit;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.state
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String state;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column user.depart
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private String depart;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.userName
	 * @return  the value of user.userName
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.userName
	 * @param username  the value for user.userName
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.passWord
	 * @return  the value of user.passWord
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.passWord
	 * @param password  the value for user.passWord
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.credit
	 * @return  the value of user.credit
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Integer getCredit() {
		return credit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.credit
	 * @param credit  the value for user.credit
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.state
	 * @return  the value of user.state
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.state
	 * @param state  the value for user.state
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column user.depart
	 * @return  the value of user.depart
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public String getDepart() {
		return depart;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column user.depart
	 * @param depart  the value for user.depart
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void setDepart(String depart) {
		this.depart = depart;
	}
}