package org.lg.dao;

import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import org.lg.model.Record;
import org.lg.model.RecordExample;

public class RecordDAOImpl implements RecordDAO {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private SqlMapClient sqlMapClient;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public RecordDAOImpl(SqlMapClient sqlMapClient) {
		super();
		this.sqlMapClient = sqlMapClient;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int countByExample(RecordExample example) throws SQLException {
		Integer count = (Integer) sqlMapClient.queryForObject("record.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int deleteByExample(RecordExample example) throws SQLException {
		int rows = sqlMapClient.delete("record.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int deleteByPrimaryKey(Integer id) throws SQLException {
		Record key = new Record();
		key.setId(id);
		int rows = sqlMapClient.delete("record.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void insert(Record record) throws SQLException {
		sqlMapClient.insert("record.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public void insertSelective(Record record) throws SQLException {
		sqlMapClient.insert("record.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public List selectByExample(RecordExample example) throws SQLException {
		List list = sqlMapClient.queryForList("record.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public Record selectByPrimaryKey(Integer id) throws SQLException {
		Record key = new Record();
		key.setId(id);
		Record record = (Record) sqlMapClient.queryForObject("record.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int updateByExampleSelective(Record record, RecordExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("record.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int updateByExample(Record record, RecordExample example) throws SQLException {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = sqlMapClient.update("record.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int updateByPrimaryKeySelective(Record record) throws SQLException {
		int rows = sqlMapClient.update("record.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	public int updateByPrimaryKey(Record record) throws SQLException {
		int rows = sqlMapClient.update("record.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table record
	 * @ibatorgenerated  Wed Dec 16 18:30:16 CST 2015
	 */
	private static class UpdateByExampleParms extends RecordExample {
		private Object record;

		public UpdateByExampleParms(Object record, RecordExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}